from __future__ import annotations
import datetime
from pathlib import Path
from typing import Any


class MarkdownReporter:
    """
    Generates a structured REPORT.md from experiment summaries.
    """

    def __init__(self, output_path: Path, figures_dir: Path):
        self.output_path = Path(output_path)
        self.figures_dir = Path(figures_dir)

    def generate(
        self,
        flat_rows: list[dict[str, Any]],
        ablation_table: list[dict[str, Any]],
        success_rates: dict[str, float],
        skipped: list[tuple[str, str]] | None = None,
        framework_version: str = "1.0.0",
    ) -> str:
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        lines: list[str] = [
            f"# Physical Design Experiment Report",
            f"",
            f"Generated: {now}  |  Framework v{framework_version}",
            f"",
            "---",
            "",
            "## 1. Executive Summary",
            "",
            f"- Total runs recorded: **{len(flat_rows)}**",
            f"- Designs evaluated: **{len({r.get('design') for r in flat_rows})}**",
            "",
        ]

        if success_rates:
            lines += ["## 2. Success Rates", ""]
            lines += ["| Design | Success Rate |", "|--------|-------------|"]
            for d, r in sorted(success_rates.items()):
                lines.append(f"| {d} | {r:.0%} |")
            lines.append("")

        if flat_rows:
            lines += ["## 3. QoR Results", ""]
            cols = ["design", "seed", "wns", "tns", "overflow",
                    "drc_violations", "wirelength", "total_runtime_s"]
            header = " | ".join(cols)
            sep = " | ".join(["---"] * len(cols))
            lines.append(f"| {header} |")
            lines.append(f"| {sep} |")
            for row in flat_rows:
                cells = " | ".join(str(row.get(c, "N/A")) for c in cols)
                lines.append(f"| {cells} |")
            lines.append("")

        if ablation_table:
            lines += ["## 4. Ablation Study", ""]
            if ablation_table:
                cols = list(ablation_table[0].keys())
                header = " | ".join(cols)
                sep = " | ".join(["---"] * len(cols))
                lines.append(f"| {header} |")
                lines.append(f"| {sep} |")
                for row in ablation_table:
                    cells = " | ".join(str(row.get(c, "N/A")) for c in cols)
                    lines.append(f"| {cells} |")
            lines.append("")

        lines += ["## 5. Figures", ""]
        for fig in sorted(self.figures_dir.glob("*.png")):
            rel = fig.relative_to(self.figures_dir.parent)
            lines.append(f"![{fig.stem}]({rel})")
            lines.append("")

        if skipped:
            lines += ["## 6. Skipped Circuits", ""]
            lines += ["| Circuit | Reason |", "|---------|--------|"]
            for name, reason in skipped:
                lines.append(f"| {name} | {reason} |")
            lines.append("")

        lines += [
            "## 7. Assumptions and Limitations",
            "",
            "- Results depend on PDK collateral and synthesis quality.",
            "- ISCAS combinational circuits are skipped (no clock domain).",
            "- Timing values are post-layout estimates; sign-off requires "
            "full parasitics extraction.",
            "- DRC/antenna results require a complete PDK DRC rule deck.",
            "",
            "---",
            f"*Auto-generated by the Physical Design Framework*",
        ]

        report = "\n".join(lines)
        self.output_path.write_text(report)
        return report
